# Generated by Django 4.0.6 on 2022-07-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.IntegerField(max_length=11)),
                ('assunto', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=800)),
            ],
        ),
    ]
