# Generated by Django 4.0.6 on 2022-07-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contato_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_inscrito', models.CharField(max_length=255)),
            ],
        ),
    ]
